"""
create_db.py  –  Run once to create and seed jobs.db  (~500 listings)
Usage:  python create_db.py

Schema:
  work_mode  →  remote | hybrid | onsite
  job_type   →  full-time | part-time | internship | contract
"""

import sqlite3, os

_ROOT = os.path.dirname(os.path.abspath(__file__))
_DATA = os.path.abspath(os.getenv("SKILLMATCH_DATA_DIR", _ROOT))
DB_PATH = os.path.join(_DATA, "jobs.db")

CREATE_TABLE = """
CREATE TABLE IF NOT EXISTS jobs (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    job_title       TEXT NOT NULL,
    company         TEXT NOT NULL,
    location        TEXT NOT NULL,
    work_mode       TEXT NOT NULL,
    job_type        TEXT NOT NULL,
    description     TEXT,
    required_skills TEXT,
    salary_range    TEXT,
    apply_link      TEXT NOT NULL,
    posted_date     TEXT DEFAULT (date('now'))
);
"""

# (job_title, company, location, work_mode, job_type, description, required_skills, salary_range, apply_link)
JOBS = [
    # DATA SCIENCE
    ("Data Scientist","Google","Bangalore","hybrid","full-time","Build ML models for Search & Ads.","Python,ML,TensorFlow,SQL","₹20L–₹35L","https://careers.google.com"),
    ("Data Scientist","Flipkart","Bangalore","onsite","full-time","Product analytics and recommendation systems.","Python,Statistics,Spark,SQL","₹18L–₹30L","https://www.flipkart.com/careers"),
    ("Data Scientist","Razorpay","Remote","remote","full-time","Fraud detection and risk modelling.","Python,ML,SQL,PySpark","₹22L–₹38L","https://razorpay.com/jobs"),
    ("Data Scientist","Ola","Bangalore","hybrid","full-time","Demand forecasting and driver analytics.","Python,ML,Spark,SQL","₹16L–₹28L","https://ola.careers"),
    ("Data Scientist","Paytm","Noida","hybrid","full-time","Credit risk modelling for lending products.","Python,Statistics,ML,SQL","₹15L–₹26L","https://paytm.com/careers"),
    ("Data Scientist","Meesho","Bangalore","remote","full-time","Seller analytics and growth models.","Python,Sklearn,SQL,Spark","₹18L–₹32L","https://meesho.io/jobs"),
    ("Data Scientist","Swiggy","Bangalore","hybrid","full-time","Food demand and pricing ML models.","Python,TensorFlow,SQL","₹20L–₹36L","https://bytes.swiggy.com/careers"),
    ("Data Scientist","Hotstar","Mumbai","hybrid","full-time","Content recommendation and user engagement.","Python,ML,Spark,SQL","₹22L–₹38L","https://careers.hotstar.com"),
    ("Data Scientist","Urban Company","Gurgaon","hybrid","full-time","Service matching and quality prediction.","Python,ML,SQL","₹14L–₹24L","https://urbancompany.com/careers"),
    ("Data Scientist","Byju's","Bangalore","onsite","full-time","Learning outcome prediction models.","Python,Statistics,ML","₹16L–₹28L","https://byjus.com/careers"),
    ("Data Scientist","Nykaa","Mumbai","hybrid","full-time","Beauty product recommendation engine.","Python,ML,SQL,Looker","₹14L–₹24L","https://careers.nykaa.com"),
    ("Data Scientist","PolicyBazaar","Gurgaon","hybrid","full-time","Insurance risk and pricing models.","Python,ML,SQL","₹16L–₹28L","https://www.policybazaar.com/careers"),
    ("Data Scientist","Freshworks","Chennai","hybrid","full-time","CRM intelligence and churn prediction.","Python,ML,SQL","₹16L–₹28L","https://www.freshworks.com/company/careers"),
    ("Data Scientist","Zomato","Gurgaon","hybrid","full-time","Delivery time and restaurant recommendation.","Python,ML,SQL,Spark","₹18L–₹32L","https://www.zomato.com/careers"),
    ("Data Scientist","Dunzo","Bangalore","remote","full-time","Quick-commerce demand and route prediction.","Python,ML,SQL","₹15L–₹25L","https://www.dunzo.com/careers"),
    ("Data Scientist","Groww","Bangalore","hybrid","full-time","Investment product personalization models.","Python,Statistics,ML,SQL","₹18L–₹30L","https://groww.in/about/careers"),
    ("Data Scientist","Lenskart","Remote","remote","full-time","Customer segmentation and retention models.","Python,ML,SQL","₹15L–₹26L","https://careers.lenskart.com"),
    ("Data Scientist","ShareChat","Bangalore","remote","full-time","Social content ranking and personalisation.","Python,ML,Spark,SQL","₹18L–₹32L","https://sharechat.com/careers"),
    ("Data Scientist","Slice","Bangalore","hybrid","full-time","Credit scoring and risk models.","Python,Statistics,ML,SQL","₹16L–₹28L","https://sliceit.com/careers"),
    ("Data Scientist","MakeMyTrip","Gurgaon","hybrid","full-time","Travel pricing and demand models.","Python,ML,SQL,Spark","₹16L–₹28L","https://careers.makemytrip.com"),
    ("Senior Data Scientist","Amazon","Hyderabad","hybrid","full-time","Lead ML projects for Alexa and AWS.","Python,ML,Spark,AWS,SageMaker","₹35L–₹60L","https://amazon.jobs"),
    ("Senior Data Scientist","Microsoft","Hyderabad","hybrid","full-time","AI research for Azure cognitive services.","Python,ML,Azure,PyTorch","₹38L–₹65L","https://careers.microsoft.com"),
    ("Senior Data Scientist","Walmart Labs","Bangalore","hybrid","full-time","Supply chain optimization models.","Python,ML,Spark,Scala","₹32L–₹55L","https://careers.walmart.com"),
    ("Lead Data Scientist","Juspay","Bangalore","hybrid","full-time","Lead fraud and risk ML team.","Python,ML,MLFlow,Kafka","₹30L–₹50L","https://juspay.in/careers"),
    ("Data Scientist Intern","Analytics Vidhya","Remote","remote","internship","NLP and generative AI research.","Python,NLP,HuggingFace","₹30K–₹50K/mo","https://www.analyticsvidhya.com/jobs"),
    ("Data Scientist Intern","Myntra","Bangalore","hybrid","internship","Fashion recommendation research.","Python,ML,SQL","₹25K–₹40K/mo","https://careers.myntra.com"),
    ("Data Scientist Intern","PhonePe","Bangalore","onsite","internship","Payments analytics intern.","Python,SQL,Statistics","₹20K–₹35K/mo","https://careers.phonepe.com"),
    ("Data Scientist Intern","Swiggy","Bangalore","hybrid","internship","Food demand ML intern.","Python,ML,SQL","₹22K–₹38K/mo","https://bytes.swiggy.com/careers"),

    # MACHINE LEARNING ENGINEERING
    ("Machine Learning Engineer","Amazon","Hyderabad","hybrid","full-time","Deploy production ML pipelines on AWS.","Python,SageMaker,MLOps,Docker","₹25L–₹45L","https://amazon.jobs"),
    ("Machine Learning Engineer","Swiggy","Bangalore","onsite","full-time","ETA prediction and demand forecasting.","Python,TensorFlow,SQL,Kafka","₹20L–₹36L","https://bytes.swiggy.com/careers"),
    ("Machine Learning Engineer","Juspay","Remote","remote","full-time","Payment fraud ML systems.","Python,Sklearn,SQL,MLFlow","₹18L–₹32L","https://juspay.in/careers"),
    ("Machine Learning Engineer","Flipkart","Bangalore","hybrid","full-time","Catalogue quality and search ranking.","Python,TensorFlow,Spark,SQL","₹22L–₹38L","https://www.flipkart.com/careers"),
    ("Machine Learning Engineer","Ola","Bangalore","hybrid","full-time","Maps and navigation ML pipeline.","Python,TensorFlow,Go,Kafka","₹20L–₹35L","https://ola.careers"),
    ("Machine Learning Engineer","CRED","Bangalore","hybrid","full-time","Credit scoring and anomaly detection.","Python,ML,Spark,Docker","₹22L–₹40L","https://careers.cred.club"),
    ("Machine Learning Engineer","ShareChat","Bangalore","remote","full-time","Content moderation and ranking models.","Python,PyTorch,MLOps,Kafka","₹20L–₹36L","https://sharechat.com/careers"),
    ("Machine Learning Engineer","PhonePe","Bangalore","hybrid","full-time","Fraud detection and payment ML.","Python,TensorFlow,Spark,Kafka","₹22L–₹38L","https://careers.phonepe.com"),
    ("Machine Learning Engineer","Meesho","Remote","remote","full-time","Product recommendation ML systems.","Python,Sklearn,MLFlow,SQL","₹18L–₹32L","https://meesho.io/jobs"),
    ("Machine Learning Engineer","Zomato","Gurgaon","hybrid","full-time","Delivery ETA and route ML models.","Python,TensorFlow,SQL,Docker","₹20L–₹36L","https://www.zomato.com/careers"),
    ("MLOps Engineer","Razorpay","Bangalore","hybrid","full-time","Build and maintain ML infrastructure.","Python,Kubernetes,MLFlow,Airflow","₹20L–₹36L","https://razorpay.com/jobs"),
    ("MLOps Engineer","PhonePe","Bangalore","hybrid","full-time","Model serving and monitoring at scale.","Python,Docker,Kubernetes,Airflow","₹22L–₹38L","https://careers.phonepe.com"),
    ("MLOps Engineer","Flipkart","Bangalore","hybrid","full-time","ML platform and model lifecycle.","Python,Kubernetes,Airflow,Spark","₹22L–₹40L","https://www.flipkart.com/careers"),
    ("ML Research Intern","Microsoft","Hyderabad","hybrid","internship","Research on LLMs and responsible AI.","Python,PyTorch,NLP,Transformers","Stipend","https://careers.microsoft.com"),
    ("ML Research Intern","Google","Bangalore","hybrid","internship","Research on multimodal models.","Python,TensorFlow,Research","Stipend","https://careers.google.com"),
    ("ML Engineer Intern","Amazon","Hyderabad","onsite","internship","Build ML features for Alexa.","Python,ML,AWS","₹25K–₹40K/mo","https://amazon.jobs"),
    ("ML Engineer Intern","Swiggy","Bangalore","hybrid","internship","Demand forecasting ML intern.","Python,ML,SQL","₹22K–₹38K/mo","https://bytes.swiggy.com/careers"),

    # SOFTWARE ENGINEERING
    ("Software Engineer","Microsoft","Hyderabad","hybrid","full-time","Backend services for Azure cloud platform.","Java,C#,.NET,SQL,Azure","₹22L–₹40L","https://careers.microsoft.com"),
    ("Software Engineer","Infosys","Pune","onsite","full-time","Enterprise application development.","Java,Spring Boot,SQL,REST","₹8L–₹14L","https://www.infosys.com/careers"),
    ("Software Engineer","Zepto","Remote","remote","full-time","Microservices for quick-commerce platform.","Go,Kubernetes,PostgreSQL,gRPC","₹18L–₹30L","https://www.zepto.team/careers"),
    ("Software Engineer","Postman","Bangalore","hybrid","full-time","Core API platform engineering.","Node.js,TypeScript,MongoDB,AWS","₹20L–₹35L","https://www.postman.com/company/careers"),
    ("Software Engineer","Freshworks","Chennai","hybrid","full-time","SaaS CRM platform development.","Ruby,Rails,PostgreSQL,React","₹14L–₹24L","https://www.freshworks.com/company/careers"),
    ("Software Engineer","Razorpay","Bangalore","hybrid","full-time","Payments infrastructure and APIs.","Java,Go,MySQL,Kafka","₹22L–₹38L","https://razorpay.com/jobs"),
    ("Software Engineer","PhonePe","Bangalore","hybrid","full-time","Build high-throughput payment systems.","Java,Spring,Kafka,MySQL","₹20L–₹36L","https://careers.phonepe.com"),
    ("Software Engineer","Flipkart","Bangalore","hybrid","full-time","Platform engineering and microservices.","Java,Spring,MySQL,Kafka","₹22L–₹40L","https://www.flipkart.com/careers"),
    ("Software Engineer","Zomato","Gurgaon","hybrid","full-time","Order management and logistics systems.","Go,Python,MySQL,Redis","₹18L–₹32L","https://www.zomato.com/careers"),
    ("Software Engineer","Ola","Bangalore","onsite","full-time","Ride-matching and dispatch systems.","Java,Go,Kafka,Redis","₹16L–₹28L","https://ola.careers"),
    ("Software Engineer","CRED","Bangalore","hybrid","full-time","Fintech platform core engineering.","Kotlin,Java,PostgreSQL,Kafka","₹20L–₹36L","https://careers.cred.club"),
    ("Software Engineer","Meesho","Bangalore","remote","full-time","Social commerce platform services.","Python,Java,MySQL,gRPC","₹18L–₹32L","https://meesho.io/jobs"),
    ("Software Engineer","Groww","Bangalore","hybrid","full-time","Trading platform backend.","Java,Spring,MySQL,Kafka","₹18L–₹32L","https://groww.in/about/careers"),
    ("Software Engineer","BrowserStack","Mumbai","hybrid","full-time","Testing infrastructure platform.","Ruby,Node.js,Python,AWS","₹18L–₹32L","https://www.browserstack.com/careers"),
    ("Software Engineer","Hotstar","Mumbai","hybrid","full-time","Live streaming and content delivery.","Go,Python,Kafka,AWS","₹20L–₹36L","https://careers.hotstar.com"),
    ("Software Engineer","Dunzo","Bangalore","remote","full-time","Quick commerce logistics platform.","Python,Go,PostgreSQL","₹15L–₹26L","https://www.dunzo.com/careers"),
    ("Software Engineer","Slice","Bangalore","hybrid","full-time","Fintech card and payments platform.","Java,Spring,MySQL,Redis","₹16L–₹28L","https://sliceit.com/careers"),
    ("Software Engineer","Juspay","Remote","remote","full-time","Payments router and orchestration.","Haskell,Java,PostgreSQL","₹18L–₹32L","https://juspay.in/careers"),
    ("Software Engineer","Lenskart","Remote","remote","full-time","E-commerce platform development.","Python,Node.js,MySQL,Redis","₹14L–₹24L","https://careers.lenskart.com"),
    ("Software Engineer","MakeMyTrip","Gurgaon","hybrid","full-time","Travel booking platform services.","Java,Spring,MySQL,Redis","₹16L–₹28L","https://careers.makemytrip.com"),
    ("Software Engineer","Nykaa","Mumbai","hybrid","full-time","E-commerce and beauty platform.","Python,Node.js,MySQL","₹14L–₹24L","https://careers.nykaa.com"),
    ("Software Engineer","Urban Company","Gurgaon","hybrid","full-time","Services marketplace platform.","Node.js,Python,PostgreSQL","₹16L–₹28L","https://urbancompany.com/careers"),
    ("Software Engineer","Unacademy","Bangalore","hybrid","full-time","EdTech platform engineering.","Python,Django,PostgreSQL,Redis","₹15L–₹26L","https://unacademy.com/careers"),
    ("Software Engineer","ShareChat","Bangalore","remote","full-time","Social media platform microservices.","Java,Go,Kafka,MySQL","₹18L–₹32L","https://sharechat.com/careers"),
    ("Software Engineer","Delhivery","Gurgaon","hybrid","full-time","Logistics platform and routing.","Python,Java,MySQL,Kafka","₹14L–₹24L","https://www.delhivery.com/careers"),
    ("Software Engineer","Byju's","Bangalore","onsite","full-time","Learning platform services.","Java,Spring,MySQL,Redis","₹14L–₹24L","https://byjus.com/careers"),
    ("Software Engineer","Druva","Pune","remote","full-time","Cloud-native data protection platform.","Go,Python,AWS,MySQL","₹20L–₹36L","https://www.druva.com/company/careers"),
    ("Software Engineer","Hasura","Remote","remote","full-time","GraphQL engine development.","Haskell,Go,PostgreSQL","₹22L–₹40L","https://hasura.io/careers"),
    ("Software Engineer","Chargebee","Chennai","hybrid","full-time","Subscription billing platform.","Ruby,Rails,MySQL,React","₹18L–₹32L","https://www.chargebee.com/careers"),
    ("Software Engineer","Zoho","Chennai","onsite","full-time","Enterprise SaaS product development.","Java,C++,MySQL,JavaScript","₹10L–₹20L","https://careers.zohocorp.com"),
    ("Software Engineer","HCL","Noida","onsite","full-time","IT services and product development.","Java,Spring,SQL,JavaScript","₹8L–₹15L","https://www.hcltech.com/careers"),
    ("Software Engineer","Wipro","Hyderabad","hybrid","full-time","Digital transformation projects.","Java,Python,SQL,Angular","₹9L–₹16L","https://careers.wipro.com"),
    ("Software Engineer","TCS","Pune","onsite","full-time","Enterprise software development.","Java,Spring,SQL,JavaScript","₹8L–₹14L","https://www.tcs.com/careers"),
    ("Software Engineer","Infosys","Bangalore","hybrid","full-time","Cloud and digital engineering.","Java,Python,AWS,SQL","₹9L–₹16L","https://www.infosys.com/careers"),
    ("Software Engineer","Persistent","Pune","hybrid","full-time","Product engineering services.","Java,Angular,SQL,AWS","₹10L–₹18L","https://www.persistent.com/careers"),
    ("Software Engineer","Mphasis","Bangalore","hybrid","full-time","Fintech and cloud software engineering.","Java,Python,AWS,SQL","₹10L–₹18L","https://www.mphasis.com/careers"),
    ("Senior Software Engineer","Google","Hyderabad","hybrid","full-time","Lead backend systems for Google Cloud.","Java,Go,Kubernetes,SQL","₹40L–₹70L","https://careers.google.com"),
    ("Senior Software Engineer","Amazon","Bangalore","hybrid","full-time","Lead services for Amazon India marketplace.","Java,AWS,DynamoDB,Kafka","₹38L–₹65L","https://amazon.jobs"),
    ("Senior Software Engineer","Razorpay","Bangalore","hybrid","full-time","Lead payment infrastructure team.","Java,Go,MySQL,Kafka","₹32L–₹55L","https://razorpay.com/jobs"),
    ("Staff Software Engineer","Flipkart","Bangalore","hybrid","full-time","Technical leadership across platform.","Java,Go,Kafka,MySQL,System Design","₹45L–₹80L","https://www.flipkart.com/careers"),
    ("Software Engineering Intern","Atlassian","Remote","remote","internship","Build features for Jira and Confluence.","Java,React,SQL","₹30K–₹50K/mo","https://www.atlassian.com/company/careers"),
    ("Software Engineering Intern","Microsoft","Hyderabad","hybrid","internship","Intern on Azure or Office 365 teams.","C#,Java,Python","₹25K–₹45K/mo","https://careers.microsoft.com"),
    ("Software Engineering Intern","Freshworks","Chennai","onsite","internship","Build SaaS product features.","Ruby,React,SQL","₹20K–₹35K/mo","https://www.freshworks.com/company/careers"),
    ("Software Engineering Intern","Razorpay","Bangalore","hybrid","internship","Payments API intern.","Java,Python,SQL","₹25K–₹40K/mo","https://razorpay.com/jobs"),
    ("Software Engineering Intern","Groww","Bangalore","onsite","internship","Trading platform features.","React,Java,SQL","₹25K–₹40K/mo","https://groww.in/about/careers"),
    ("Software Engineering Intern","PhonePe","Bangalore","hybrid","internship","Payments platform intern.","Java,Python,SQL","₹22K–₹38K/mo","https://careers.phonepe.com"),
    ("Software Engineering Intern","Zomato","Gurgaon","hybrid","internship","Order platform intern.","Go,Python,SQL","₹22K–₹38K/mo","https://www.zomato.com/careers"),
    ("Contract Software Engineer","Wipro","Remote","remote","contract","6-month cloud migration project.","Java,AWS,Terraform","₹70K–₹90K/mo","https://careers.wipro.com"),
    ("Contract Software Engineer","TCS","Remote","remote","contract","Digital transformation contract role.","Java,Python,SQL","₹60K–₹80K/mo","https://www.tcs.com/careers"),
    ("Part-time Software Engineer","Remote Startup","Remote","remote","part-time","20 hrs/week product feature development.","Python,React,PostgreSQL","₹50K–₹70K/mo","https://angel.co/jobs"),

    # FRONTEND DEVELOPMENT
    ("Frontend Developer","Zomato","Gurgaon","hybrid","full-time","Consumer web for 100M+ users.","React,TypeScript,CSS,GraphQL","₹15L–₹28L","https://www.zomato.com/careers"),
    ("Frontend Developer","CRED","Bangalore","hybrid","full-time","Design-first product development.","React,Next.js,CSS,Figma","₹18L–₹32L","https://careers.cred.club"),
    ("Frontend Developer","Razorpay","Remote","remote","full-time","Payment UI components and checkout.","React,TypeScript,Webpack","₹16L–₹28L","https://razorpay.com/jobs"),
    ("Frontend Developer","Meesho","Bangalore","hybrid","full-time","Social commerce web experience.","React,Next.js,TypeScript","₹15L–₹26L","https://meesho.io/jobs"),
    ("Frontend Developer","BrowserStack","Mumbai","hybrid","full-time","Testing platform UI.","React,TypeScript,CSS","₹16L–₹28L","https://www.browserstack.com/careers"),
    ("Frontend Developer","Freshworks","Chennai","hybrid","full-time","CRM product UI components.","React,TypeScript,GraphQL","₹14L–₹24L","https://www.freshworks.com/company/careers"),
    ("Frontend Developer","Chargebee","Chennai","hybrid","full-time","Billing dashboard UI.","React,TypeScript,Tailwind","₹16L–₹28L","https://www.chargebee.com/careers"),
    ("Frontend Developer","Postman","Bangalore","hybrid","full-time","API testing UI.","React,TypeScript,Electron","₹18L–₹32L","https://www.postman.com/company/careers"),
    ("Frontend Developer","Unacademy","Bangalore","hybrid","full-time","EdTech learning UI.","React,Next.js,TypeScript","₹14L–₹24L","https://unacademy.com/careers"),
    ("Frontend Developer","ShareChat","Bangalore","remote","full-time","Social media PWA.","React,TypeScript,PWA","₹16L–₹28L","https://sharechat.com/careers"),
    ("Frontend Developer","Urban Company","Gurgaon","hybrid","full-time","Consumer services web app.","React,TypeScript,GraphQL","₹14L–₹24L","https://urbancompany.com/careers"),
    ("Frontend Developer","Slice","Bangalore","hybrid","full-time","Fintech consumer-facing UI.","React,Next.js,TypeScript","₹14L–₹26L","https://sliceit.com/careers"),
    ("Frontend Developer","Groww","Bangalore","hybrid","full-time","Investment app web platform.","React,TypeScript,Redux","₹16L–₹28L","https://groww.in/about/careers"),
    ("Frontend Developer","Hotstar","Mumbai","hybrid","full-time","Streaming web player UI.","React,TypeScript,Video.js","₹18L–₹32L","https://careers.hotstar.com"),
    ("Frontend Developer","Paytm","Noida","hybrid","full-time","Super-app web consumer UI.","React,JavaScript,CSS","₹14L–₹24L","https://paytm.com/careers"),
    ("React Developer","Zoho","Chennai","onsite","full-time","Enterprise SaaS product UI.","React,JavaScript,CSS,REST","₹10L–₹20L","https://careers.zohocorp.com"),
    ("React Developer","Druva","Remote","remote","full-time","Cloud backup product UI.","React,TypeScript,AWS Amplify","₹18L–₹32L","https://www.druva.com/company/careers"),
    ("Vue.js Developer","Hasura","Remote","remote","full-time","GraphQL console UI.","Vue.js,TypeScript,GraphQL","₹18L–₹32L","https://hasura.io/careers"),
    ("Angular Developer","TCS","Pune","hybrid","full-time","Enterprise dashboard development.","Angular,TypeScript,RxJS","₹10L–₹18L","https://www.tcs.com/careers"),
    ("Angular Developer","Infosys","Bangalore","hybrid","full-time","Digital banking portal.","Angular,TypeScript,REST","₹10L–₹18L","https://www.infosys.com/careers"),
    ("Senior Frontend Developer","Flipkart","Bangalore","hybrid","full-time","Lead frontend for buyer experience.","React,TypeScript,Micro-frontends","₹30L–₹52L","https://www.flipkart.com/careers"),
    ("Senior Frontend Developer","Swiggy","Bangalore","hybrid","full-time","Consumer ordering experience lead.","React,Next.js,TypeScript","₹28L–₹48L","https://bytes.swiggy.com/careers"),
    ("Frontend Intern","Groww","Bangalore","onsite","internship","Stock platform feature development.","React,JavaScript,HTML,CSS","₹25K–₹40K/mo","https://groww.in/about/careers"),
    ("Frontend Intern","Zomato","Gurgaon","hybrid","internship","Consumer web features.","React,JavaScript,CSS","₹20K–₹35K/mo","https://www.zomato.com/careers"),
    ("Frontend Intern","Meesho","Remote","remote","internship","Social commerce UI features.","React,JavaScript,HTML","₹20K–₹35K/mo","https://meesho.io/jobs"),
    ("Frontend Intern","Freshworks","Chennai","onsite","internship","SaaS product UI intern.","React,JavaScript,CSS","₹18K–₹30K/mo","https://www.freshworks.com/company/careers"),
    ("Part-time Frontend Developer","Remote","Remote","remote","part-time","20 hrs/week UI development.","React,TypeScript,CSS","₹40K–₹60K/mo","https://angel.co/jobs"),

    # BACKEND DEVELOPMENT
    ("Backend Developer","PhonePe","Bangalore","hybrid","full-time","Payment processing systems.","Java,Spring,Kafka,MySQL","₹20L–₹38L","https://careers.phonepe.com"),
    ("Backend Developer","Ola","Bangalore","onsite","full-time","Ride-matching backend.","Python,Django,Redis,PostgreSQL","₹16L–₹28L","https://ola.careers"),
    ("Backend Developer","Freshworks","Chennai","hybrid","full-time","SaaS CRM platform backend.","Ruby,Rails,PostgreSQL,Redis","₹14L–₹24L","https://www.freshworks.com/company/careers"),
    ("Backend Developer","Paytm","Noida","hybrid","full-time","Payments and wallet services.","Java,Spring,MySQL,Kafka","₹16L–₹28L","https://paytm.com/careers"),
    ("Backend Developer","Nykaa","Mumbai","hybrid","full-time","E-commerce order management.","Python,Django,MySQL,Redis","₹14L–₹24L","https://careers.nykaa.com"),
    ("Backend Developer","Dunzo","Bangalore","remote","full-time","Quick delivery routing services.","Go,PostgreSQL,Redis","₹15L–₹26L","https://www.dunzo.com/careers"),
    ("Backend Developer","MakeMyTrip","Gurgaon","hybrid","full-time","Travel booking microservices.","Java,Spring,MySQL,Redis","₹16L–₹28L","https://careers.makemytrip.com"),
    ("Backend Developer","Lenskart","Remote","remote","full-time","Optical e-commerce backend.","Python,Flask,MySQL,Redis","₹14L–₹24L","https://careers.lenskart.com"),
    ("Backend Developer","Delhivery","Gurgaon","hybrid","full-time","Logistics and tracking APIs.","Python,Go,MySQL,Kafka","₹15L–₹26L","https://www.delhivery.com/careers"),
    ("Backend Developer","PolicyBazaar","Gurgaon","hybrid","full-time","Insurance aggregation APIs.","Java,Spring,MySQL","₹14L–₹24L","https://www.policybazaar.com/careers"),
    ("Backend Developer","Zepto","Remote","remote","full-time","Quick-commerce backend services.","Go,PostgreSQL,Redis,gRPC","₹18L–₹32L","https://www.zepto.team/careers"),
    ("Backend Developer","Slice","Bangalore","hybrid","full-time","Credit card platform services.","Java,Spring,MySQL,Redis","₹16L–₹28L","https://sliceit.com/careers"),
    ("Backend Developer","Byju's","Bangalore","onsite","full-time","EdTech content delivery APIs.","Node.js,MongoDB,Redis","₹14L–₹24L","https://byjus.com/careers"),
    ("Backend Developer","Hotstar","Mumbai","hybrid","full-time","Live streaming APIs.","Go,Python,Kafka,Redis","₹18L–₹32L","https://careers.hotstar.com"),
    ("Backend Developer","Groww","Bangalore","hybrid","full-time","Investment and trading APIs.","Java,Spring,MySQL,Kafka","₹16L–₹28L","https://groww.in/about/careers"),
    ("Node.js Developer","Urban Company","Gurgaon","hybrid","full-time","Marketplace services API.","Node.js,TypeScript,PostgreSQL","₹16L–₹28L","https://urbancompany.com/careers"),
    ("Node.js Developer","Chargebee","Chennai","hybrid","full-time","Billing API development.","Node.js,TypeScript,MySQL","₹16L–₹28L","https://www.chargebee.com/careers"),
    ("Go Developer","Hotstar","Mumbai","hybrid","full-time","Live streaming backend.","Go,Kafka,AWS,Redis","₹20L–₹36L","https://careers.hotstar.com"),
    ("Go Developer","Zepto","Remote","remote","full-time","High-performance microservices.","Go,gRPC,PostgreSQL,Kafka","₹20L–₹36L","https://www.zepto.team/careers"),
    ("Python Developer","Razorpay","Bangalore","hybrid","full-time","Data and automation services.","Python,FastAPI,PostgreSQL,Celery","₹18L–₹32L","https://razorpay.com/jobs"),
    ("Python Developer","Meesho","Remote","remote","full-time","Seller platform APIs.","Python,Django,MySQL,Redis","₹16L–₹28L","https://meesho.io/jobs"),
    ("Java Developer","Wipro","Hyderabad","hybrid","full-time","Enterprise Java application development.","Java,Spring Boot,SQL,REST","₹10L–₹18L","https://careers.wipro.com"),
    ("Java Developer","TCS","Pune","onsite","full-time","Banking application development.","Java,Spring,Hibernate,SQL","₹9L–₹16L","https://www.tcs.com/careers"),
    ("Senior Backend Developer","Google","Hyderabad","hybrid","full-time","Core search and infrastructure.","Java,Go,Kubernetes,Spanner","₹40L–₹70L","https://careers.google.com"),
    ("Backend Intern","Meesho","Remote","remote","internship","Social commerce APIs.","Python,FastAPI,SQL","₹20K–₹35K/mo","https://meesho.io/jobs"),
    ("Backend Intern","Razorpay","Bangalore","hybrid","internship","Payments API intern.","Java,Spring,SQL","₹25K–₹40K/mo","https://razorpay.com/jobs"),
    ("Backend Intern","Freshworks","Chennai","onsite","internship","CRM API features.","Ruby,SQL,REST","₹20K–₹35K/mo","https://www.freshworks.com/company/careers"),
    ("Backend Intern","Zomato","Gurgaon","hybrid","internship","Restaurant and order APIs.","Go,Python,SQL","₹22K–₹38K/mo","https://www.zomato.com/careers"),
    ("Backend Intern","PhonePe","Bangalore","hybrid","internship","Payments backend intern.","Java,Spring,SQL","₹22K–₹38K/mo","https://careers.phonepe.com"),
    ("Contract Backend Developer","HCL","Remote","remote","contract","6-month API modernization project.","Java,Spring,REST,SQL","₹70K–₹90K/mo","https://www.hcltech.com/careers"),
    ("Part-time Backend Developer","Remote","Remote","remote","part-time","Weekend API development.","Python,FastAPI,PostgreSQL","₹45K–₹65K/mo","https://angel.co/jobs"),

    # FULL STACK
    ("Full Stack Developer","Notion","Remote","remote","full-time","Collaborative productivity features.","React,Node.js,TypeScript,PostgreSQL","₹22L–₹40L","https://www.notion.so/careers"),
    ("Full Stack Developer","Hasura","Remote","remote","full-time","GraphQL engine and cloud platform.","React,Go,PostgreSQL,TypeScript","₹20L–₹36L","https://hasura.io/careers"),
    ("Full Stack Developer","BrowserStack","Mumbai","hybrid","full-time","Testing platform UI and APIs.","React,Node.js,Ruby,AWS","₹18L–₹32L","https://www.browserstack.com/careers"),
    ("Full Stack Developer","Zoho","Chennai","onsite","full-time","Enterprise SaaS product development.","Java,React,MySQL,JavaScript","₹10L–₹20L","https://careers.zohocorp.com"),
    ("Full Stack Developer","Chargebee","Chennai","hybrid","full-time","Subscription billing product.","Ruby,React,MySQL,TypeScript","₹18L–₹32L","https://www.chargebee.com/careers"),
    ("Full Stack Developer","Freshworks","Chennai","hybrid","full-time","CRM product features end-to-end.","Ruby,React,PostgreSQL","₹16L–₹28L","https://www.freshworks.com/company/careers"),
    ("Full Stack Developer","Urban Company","Gurgaon","hybrid","full-time","Marketplace product features.","Node.js,React,PostgreSQL","₹16L–₹28L","https://urbancompany.com/careers"),
    ("Full Stack Developer","Unacademy","Bangalore","hybrid","full-time","EdTech learning experience.","Python,React,PostgreSQL,Redis","₹14L–₹26L","https://unacademy.com/careers"),
    ("Full Stack Developer","Slice","Bangalore","hybrid","full-time","Fintech consumer product.","Node.js,React,MySQL,Redis","₹16L–₹28L","https://sliceit.com/careers"),
    ("Full Stack Developer","Lenskart","Remote","remote","full-time","Optical e-commerce product.","Python,React,MySQL,Redis","₹14L–₹24L","https://careers.lenskart.com"),
    ("Full Stack Developer","PolicyBazaar","Gurgaon","hybrid","full-time","Insurance platform features.","Java,Angular,MySQL","₹14L–₹24L","https://www.policybazaar.com/careers"),
    ("Full Stack Developer","Delhivery","Gurgaon","hybrid","full-time","Logistics product development.","Python,React,MySQL,Redis","₹14L–₹24L","https://www.delhivery.com/careers"),
    ("MERN Stack Developer","ShareChat","Remote","remote","full-time","Social media product development.","MongoDB,Express,React,Node.js","₹16L–₹28L","https://sharechat.com/careers"),
    ("MERN Stack Developer","Dunzo","Remote","remote","full-time","Quick commerce product.","MongoDB,Express,React,Node.js","₹15L–₹26L","https://www.dunzo.com/careers"),
    ("Full Stack Intern","Groww","Bangalore","onsite","internship","Investment platform features.","React,Node.js,SQL","₹25K–₹40K/mo","https://groww.in/about/careers"),
    ("Full Stack Intern","BrowserStack","Mumbai","hybrid","internship","Testing platform intern.","React,Node.js,Ruby","₹22K–₹38K/mo","https://www.browserstack.com/careers"),
    ("Full Stack Intern","Chargebee","Chennai","onsite","internship","Billing product features.","React,Ruby,SQL","₹20K–₹35K/mo","https://www.chargebee.com/careers"),
    ("Full Stack Intern","Urban Company","Gurgaon","hybrid","internship","Services marketplace intern.","React,Node.js,SQL","₹20K–₹35K/mo","https://urbancompany.com/careers"),
    ("Part-time Full Stack Developer","Remote","Remote","remote","part-time","Freelance product development.","React,Node.js,PostgreSQL","₹45K–₹65K/mo","https://angel.co/jobs"),

    # DATA ANALYTICS
    ("Data Analyst","Paytm","Noida","hybrid","full-time","Business analytics for payments.","SQL,Python,Tableau,Excel","₹8L–₹16L","https://paytm.com/careers"),
    ("Data Analyst","MakeMyTrip","Gurgaon","onsite","full-time","Travel demand and pricing analytics.","SQL,Excel,Python,PowerBI","₹9L–₹16L","https://careers.makemytrip.com"),
    ("Data Analyst","Nykaa","Mumbai","hybrid","full-time","E-commerce analytics.","SQL,Python,Looker,Excel","₹8L–₹14L","https://careers.nykaa.com"),
    ("Data Analyst","Urban Company","Gurgaon","hybrid","full-time","Services marketplace analytics.","SQL,Python,Tableau","₹9L–₹16L","https://urbancompany.com/careers"),
    ("Data Analyst","Meesho","Remote","remote","full-time","Seller and buyer growth analytics.","SQL,Python,Metabase","₹9L–₹16L","https://meesho.io/jobs"),
    ("Data Analyst","Delhivery","Remote","remote","full-time","Logistics operations analytics.","SQL,Python,PowerBI,Excel","₹8L–₹15L","https://www.delhivery.com/careers"),
    ("Data Analyst","Byju's","Bangalore","hybrid","full-time","Student engagement analytics.","SQL,Python,Tableau","₹8L–₹14L","https://byjus.com/careers"),
    ("Data Analyst","Dunzo","Remote","remote","full-time","Quick commerce ops analytics.","SQL,Python,Looker","₹8L–₹15L","https://www.dunzo.com/careers"),
    ("Data Analyst","Lenskart","Remote","remote","full-time","Optical retail analytics.","SQL,Python,PowerBI","₹8L–₹14L","https://careers.lenskart.com"),
    ("Data Analyst","PolicyBazaar","Gurgaon","hybrid","full-time","Insurance product analytics.","SQL,Python,Tableau,Excel","₹8L–₹15L","https://www.policybazaar.com/careers"),
    ("Data Analyst","Slice","Bangalore","hybrid","full-time","Credit product analytics.","SQL,Python,Metabase","₹9L–₹16L","https://sliceit.com/careers"),
    ("Data Analyst","ShareChat","Remote","remote","full-time","Content and engagement analytics.","SQL,Python,Looker","₹10L–₹18L","https://sharechat.com/careers"),
    ("Data Analyst","Hotstar","Mumbai","hybrid","full-time","Streaming platform analytics.","SQL,Python,Tableau,Spark","₹10L–₹18L","https://careers.hotstar.com"),
    ("Data Analyst","Flipkart","Bangalore","hybrid","full-time","Marketplace seller analytics.","SQL,Python,Spark,Tableau","₹10L–₹18L","https://www.flipkart.com/careers"),
    ("Data Analyst","Groww","Bangalore","hybrid","full-time","Investment product analytics.","SQL,Python,Amplitude","₹10L–₹18L","https://groww.in/about/careers"),
    ("Business Analyst","Accenture","Remote","remote","full-time","Digital transformation consulting.","Excel,SQL,Tableau,Business Analysis","₹8L–₹16L","https://www.accenture.com/in-en/careers"),
    ("Business Analyst","Deloitte","Mumbai","hybrid","full-time","Strategy and data consulting.","Excel,SQL,PowerPoint,Python","₹10L–₹18L","https://www2.deloitte.com/in/en/careers"),
    ("Business Analyst","EY","Bangalore","hybrid","full-time","Technology consulting and analytics.","Excel,SQL,Tableau,Consulting","₹10L–₹18L","https://www.ey.com/en_in/careers"),
    ("Business Analyst","KPMG","Mumbai","hybrid","full-time","Advisory and analytics practice.","Excel,SQL,PowerBI,Consulting","₹10L–₹18L","https://kpmg.com/in/en/home/careers.html"),
    ("Product Analyst","Swiggy","Bangalore","hybrid","full-time","Food delivery product metrics.","SQL,Python,Amplitude,Metabase","₹12L–₹22L","https://bytes.swiggy.com/careers"),
    ("Product Analyst","CRED","Bangalore","hybrid","full-time","Fintech product analytics.","SQL,Python,Amplitude","₹14L–₹24L","https://careers.cred.club"),
    ("Product Analyst","Hotstar","Mumbai","hybrid","full-time","Streaming product metrics.","SQL,Python,Tableau","₹12L–₹22L","https://careers.hotstar.com"),
    ("Product Analyst","Razorpay","Bangalore","hybrid","full-time","Payments product analytics.","SQL,Python,Looker","₹12L–₹22L","https://razorpay.com/jobs"),
    ("Senior Data Analyst","Flipkart","Bangalore","hybrid","full-time","Lead marketplace analytics.","SQL,Python,Spark,Tableau","₹20L–₹36L","https://www.flipkart.com/careers"),
    ("Senior Data Analyst","Razorpay","Bangalore","hybrid","full-time","Lead payments analytics.","SQL,Python,Looker","₹18L–₹32L","https://razorpay.com/jobs"),
    ("Data Analyst Intern","Delhivery","Remote","remote","internship","Logistics data analysis.","SQL,Excel,Python","₹15K–₹25K/mo","https://www.delhivery.com/careers"),
    ("Data Analyst Intern","Paytm","Noida","hybrid","internship","Payments analytics intern.","SQL,Excel,Python","₹18K–₹30K/mo","https://paytm.com/careers"),
    ("Data Analyst Intern","Zomato","Gurgaon","hybrid","internship","Food delivery analytics.","SQL,Excel,Python","₹18K–₹30K/mo","https://www.zomato.com/careers"),
    ("Data Analyst Intern","Swiggy","Bangalore","hybrid","internship","Food platform analytics intern.","SQL,Python,Excel","₹18K–₹30K/mo","https://bytes.swiggy.com/careers"),
    ("Business Analyst Intern","Deloitte","Remote","remote","internship","Strategy projects intern.","Excel,PowerPoint,SQL","₹20K–₹35K/mo","https://www2.deloitte.com/in/en/careers"),
    ("Business Analyst Intern","Accenture","Remote","remote","internship","Digital consulting intern.","Excel,SQL,PowerPoint","₹18K–₹30K/mo","https://www.accenture.com/in-en/careers"),
    ("Part-time Data Analyst","Remote","Remote","remote","part-time","15 hrs/week analytics consulting.","SQL,Python,Tableau","₹35K–₹55K/mo","https://angel.co/jobs"),

    # DEVOPS / CLOUD / SRE
    ("DevOps Engineer","Hotstar","Mumbai","hybrid","full-time","CI/CD, Kubernetes and streaming infra.","Docker,Kubernetes,Terraform,AWS","₹18L–₹34L","https://careers.hotstar.com"),
    ("DevOps Engineer","Druva","Remote","remote","full-time","Cloud-native SaaS platform reliability.","AWS,Terraform,Python,Ansible","₹20L–₹36L","https://www.druva.com/company/careers"),
    ("DevOps Engineer","Razorpay","Bangalore","hybrid","full-time","Payments infrastructure reliability.","Kubernetes,Terraform,Python,AWS","₹20L–₹36L","https://razorpay.com/jobs"),
    ("DevOps Engineer","PhonePe","Bangalore","hybrid","full-time","Platform reliability and CI/CD.","Kubernetes,Docker,Terraform,GCP","₹20L–₹36L","https://careers.phonepe.com"),
    ("DevOps Engineer","Flipkart","Bangalore","hybrid","full-time","E-commerce platform infra.","Kubernetes,Docker,Terraform,AWS","₹22L–₹38L","https://www.flipkart.com/careers"),
    ("DevOps Engineer","Meesho","Remote","remote","full-time","Social commerce infrastructure.","Kubernetes,Terraform,AWS","₹18L–₹32L","https://meesho.io/jobs"),
    ("DevOps Engineer","Freshworks","Chennai","hybrid","full-time","SaaS platform reliability.","Kubernetes,Docker,Terraform,GCP","₹18L–₹32L","https://www.freshworks.com/company/careers"),
    ("DevOps Engineer","BrowserStack","Mumbai","hybrid","full-time","Testing infrastructure.","Kubernetes,Terraform,AWS,Ansible","₹18L–₹32L","https://www.browserstack.com/careers"),
    ("DevOps Engineer","Chargebee","Chennai","hybrid","full-time","Billing platform reliability.","Kubernetes,Terraform,AWS","₹18L–₹32L","https://www.chargebee.com/careers"),
    ("DevOps Engineer","Swiggy","Bangalore","hybrid","full-time","Delivery platform infra.","Kubernetes,Terraform,AWS,Prometheus","₹20L–₹36L","https://bytes.swiggy.com/careers"),
    ("DevOps Engineer","Zomato","Gurgaon","hybrid","full-time","Food platform infra and reliability.","Kubernetes,Docker,Terraform,GCP","₹18L–₹32L","https://www.zomato.com/careers"),
    ("Cloud Engineer","TCS","Pune","hybrid","full-time","Cloud migration and managed services.","AWS,Azure,Terraform,Linux","₹10L–₹20L","https://www.tcs.com/careers"),
    ("Cloud Engineer","Infosys","Bangalore","hybrid","full-time","Enterprise cloud solutions.","AWS,Azure,Terraform,Python","₹12L–₹22L","https://www.infosys.com/careers"),
    ("Cloud Engineer","Wipro","Hyderabad","hybrid","full-time","Cloud infrastructure and DevOps.","AWS,GCP,Terraform,Docker","₹12L–₹22L","https://careers.wipro.com"),
    ("Cloud Engineer","HCL","Noida","hybrid","full-time","Cloud-native application development.","AWS,Azure,Kubernetes,Terraform","₹12L–₹22L","https://www.hcltech.com/careers"),
    ("Site Reliability Engineer","Google","Hyderabad","hybrid","full-time","Reliability for Google Cloud services.","Go,Python,Kubernetes,SRE","₹35L–₹60L","https://careers.google.com"),
    ("Site Reliability Engineer","Amazon","Hyderabad","hybrid","full-time","AWS infrastructure reliability.","Python,Kubernetes,AWS,Linux","₹30L–₹52L","https://amazon.jobs"),
    ("Site Reliability Engineer","Flipkart","Bangalore","hybrid","full-time","Marketplace reliability engineering.","Python,Kubernetes,Prometheus","₹28L–₹48L","https://www.flipkart.com/careers"),
    ("Site Reliability Engineer","Swiggy","Bangalore","hybrid","full-time","Delivery platform uptime.","Go,Kubernetes,Prometheus,Grafana","₹26L–₹45L","https://bytes.swiggy.com/careers"),
    ("Infrastructure Engineer","Hasura","Remote","remote","full-time","Cloud-native Kubernetes infra.","Kubernetes,Terraform,GCP","₹22L–₹40L","https://hasura.io/careers"),
    ("DevOps Intern","Druva","Remote","remote","internship","Cloud infra automation intern.","Python,AWS,Terraform","₹20K–₹35K/mo","https://www.druva.com/company/careers"),
    ("DevOps Intern","Razorpay","Bangalore","hybrid","internship","CI/CD pipeline intern.","Docker,Kubernetes,Python","₹22K–₹38K/mo","https://razorpay.com/jobs"),
    ("DevOps Intern","PhonePe","Bangalore","hybrid","internship","Platform infra intern.","Docker,Kubernetes,Linux","₹20K–₹35K/mo","https://careers.phonepe.com"),
    ("Contract DevOps Engineer","Wipro","Remote","remote","contract","12-month Kubernetes migration.","Kubernetes,Docker,Terraform,AWS","₹80K–₹1L/mo","https://careers.wipro.com"),

    # CYBERSECURITY
    ("Cybersecurity Analyst","Wipro","Hyderabad","hybrid","full-time","SOC operations and incident response.","SIEM,Linux,Networking,Python","₹10L–₹20L","https://careers.wipro.com"),
    ("Cybersecurity Analyst","TCS","Pune","hybrid","full-time","Enterprise security monitoring.","SIEM,Splunk,Linux,Networking","₹10L–₹20L","https://www.tcs.com/careers"),
    ("Cybersecurity Analyst","Infosys","Bangalore","hybrid","full-time","Threat analysis and SOC.","SIEM,Linux,Python,OSINT","₹10L–₹20L","https://www.infosys.com/careers"),
    ("Cybersecurity Analyst","HCL","Noida","hybrid","full-time","Security operations center.","SIEM,Splunk,Linux,Networking","₹10L–₹20L","https://www.hcltech.com/careers"),
    ("Security Engineer","Razorpay","Bangalore","hybrid","full-time","Application security and pen testing.","Python,Burp Suite,OWASP,Linux","₹18L–₹30L","https://razorpay.com/jobs"),
    ("Security Engineer","PhonePe","Bangalore","hybrid","full-time","Payments platform security.","Python,OWASP,Burp Suite,Linux","₹18L–₹30L","https://careers.phonepe.com"),
    ("Security Engineer","Flipkart","Bangalore","hybrid","full-time","E-commerce platform security.","Python,SIEM,OWASP,Linux","₹18L–₹32L","https://www.flipkart.com/careers"),
    ("Security Engineer","Google","Hyderabad","hybrid","full-time","Google Cloud security engineering.","Python,Go,Linux,Cryptography","₹28L–₹50L","https://careers.google.com"),
    ("Penetration Tester","Druva","Remote","remote","full-time","Cloud security red team.","Python,Metasploit,Burp Suite,Linux","₹16L–₹28L","https://www.druva.com/company/careers"),
    ("Penetration Tester","BrowserStack","Mumbai","hybrid","full-time","Platform security testing.","Kali Linux,Metasploit,OWASP","₹15L–₹26L","https://www.browserstack.com/careers"),
    ("Information Security Analyst","Paytm","Noida","hybrid","full-time","Payments security compliance.","ISO 27001,SIEM,Python,Linux","₹12L–₹22L","https://paytm.com/careers"),
    ("Information Security Analyst","PolicyBazaar","Gurgaon","hybrid","full-time","Insurance platform security.","ISO 27001,SIEM,Python","₹10L–₹18L","https://www.policybazaar.com/careers"),
    ("Senior Security Engineer","Amazon","Hyderabad","hybrid","full-time","AWS security and compliance.","Python,AWS Security,Linux,Terraform","₹32L–₹55L","https://amazon.jobs"),
    ("Security Intern","HackerOne","Remote","remote","internship","Bug bounty platform research.","Networking,Linux,Python","Stipend","https://www.hackerone.com/company/jobs"),
    ("Security Intern","Razorpay","Bangalore","hybrid","internship","Application security intern.","Python,Linux,OWASP","₹22K–₹38K/mo","https://razorpay.com/jobs"),
    ("Security Intern","PhonePe","Bangalore","hybrid","internship","Security operations intern.","Linux,Python,SIEM","₹20K–₹35K/mo","https://careers.phonepe.com"),

    # UI/UX DESIGN
    ("UI/UX Designer","Meesho","Bangalore","hybrid","full-time","Design for 100M+ vernacular users.","Figma,Sketch,Prototyping,Research","₹12L–₹22L","https://meesho.io/jobs"),
    ("UI/UX Designer","Zomato","Gurgaon","hybrid","full-time","Consumer food ordering experience.","Figma,Design Systems,User Research","₹14L–₹24L","https://www.zomato.com/careers"),
    ("UI/UX Designer","Swiggy","Bangalore","hybrid","full-time","Delivery app design.","Figma,Prototyping,User Research","₹14L–₹24L","https://bytes.swiggy.com/careers"),
    ("UI/UX Designer","Freshworks","Chennai","hybrid","full-time","SaaS product design.","Figma,Sketch,Design Systems","₹12L–₹22L","https://www.freshworks.com/company/careers"),
    ("UI/UX Designer","BrowserStack","Mumbai","hybrid","full-time","Testing tool UX.","Figma,Prototyping,Usability Testing","₹12L–₹22L","https://www.browserstack.com/careers"),
    ("UI/UX Designer","Chargebee","Chennai","hybrid","full-time","Billing product design.","Figma,Design Systems,Prototyping","₹12L–₹22L","https://www.chargebee.com/careers"),
    ("UI/UX Designer","Urban Company","Gurgaon","hybrid","full-time","Services marketplace design.","Figma,Sketch,User Research","₹12L–₹22L","https://urbancompany.com/careers"),
    ("UI/UX Designer","Unacademy","Bangalore","hybrid","full-time","EdTech learning design.","Figma,Prototyping,Research","₹10L–₹18L","https://unacademy.com/careers"),
    ("UI/UX Designer","Lenskart","Remote","remote","full-time","Optical e-commerce design.","Figma,Prototyping,User Research","₹10L–₹18L","https://careers.lenskart.com"),
    ("UI/UX Designer","Paytm","Noida","hybrid","full-time","Super-app product design.","Figma,Sketch,Prototyping","₹12L–₹20L","https://paytm.com/careers"),
    ("UI/UX Designer","MakeMyTrip","Gurgaon","hybrid","full-time","Travel booking experience design.","Figma,Design Systems,Research","₹12L–₹20L","https://careers.makemytrip.com"),
    ("Product Designer","Razorpay","Remote","remote","full-time","Fintech product design end-to-end.","Figma,User Research,Design Systems","₹16L–₹28L","https://razorpay.com/jobs"),
    ("Product Designer","CRED","Bangalore","hybrid","full-time","Premium fintech product design.","Figma,Prototyping,Motion Design","₹18L–₹32L","https://careers.cred.club"),
    ("Product Designer","Hotstar","Mumbai","hybrid","full-time","Streaming product design.","Figma,Sketch,Prototyping","₹16L–₹28L","https://careers.hotstar.com"),
    ("Product Designer","Groww","Bangalore","hybrid","full-time","Investment app design.","Figma,Design Systems,Research","₹14L–₹24L","https://groww.in/about/careers"),
    ("Product Designer","Slice","Bangalore","hybrid","full-time","Fintech card product design.","Figma,Prototyping,Research","₹14L–₹24L","https://sliceit.com/careers"),
    ("Product Designer","PhonePe","Bangalore","hybrid","full-time","Payments product design.","Figma,Design Systems,User Research","₹16L–₹28L","https://careers.phonepe.com"),
    ("Graphic Designer","Nykaa","Mumbai","hybrid","full-time","Beauty brand and campaign design.","Illustrator,Photoshop,Figma","₹8L–₹15L","https://careers.nykaa.com"),
    ("Graphic Designer","MakeMyTrip","Gurgaon","hybrid","full-time","Travel platform visual design.","Illustrator,Photoshop,InDesign","₹8L–₹14L","https://careers.makemytrip.com"),
    ("Motion Designer","ShareChat","Remote","remote","full-time","Social content motion design.","After Effects,Premiere,Figma","₹10L–₹18L","https://sharechat.com/careers"),
    ("Senior Product Designer","Flipkart","Bangalore","hybrid","full-time","Lead buyer experience design.","Figma,Design Systems,Research","₹28L–₹48L","https://www.flipkart.com/careers"),
    ("Senior Product Designer","Swiggy","Bangalore","hybrid","full-time","Lead food ordering design.","Figma,User Research,Motion","₹26L–₹45L","https://bytes.swiggy.com/careers"),
    ("Design Intern","Canva","Remote","remote","internship","Visual design and motion graphics.","Figma,Illustrator,Motion Design","Stipend","https://www.canva.com/careers"),
    ("Design Intern","Meesho","Bangalore","hybrid","internship","Product design intern.","Figma,Sketch,Prototyping","₹18K–₹30K/mo","https://meesho.io/jobs"),
    ("Design Intern","Zomato","Gurgaon","hybrid","internship","Consumer product design intern.","Figma,Prototyping","₹18K–₹30K/mo","https://www.zomato.com/careers"),
    ("Design Intern","CRED","Bangalore","hybrid","internship","Premium product design intern.","Figma,Prototyping,Research","₹22K–₹38K/mo","https://careers.cred.club"),
    ("Design Intern","Razorpay","Bangalore","hybrid","internship","Fintech product design intern.","Figma,Prototyping","₹20K–₹35K/mo","https://razorpay.com/jobs"),
    ("Part-time UI Designer","Remote","Remote","remote","part-time","Freelance mobile UI design.","Figma,Sketch,Prototyping","₹40K–₹60K/mo","https://angel.co/jobs"),

    # PRODUCT MANAGEMENT
    ("Product Manager","Swiggy","Bangalore","onsite","full-time","Own restaurant and partner product.","Product Strategy,SQL,Agile","₹22L–₹40L","https://bytes.swiggy.com/careers"),
    ("Product Manager","Razorpay","Bangalore","hybrid","full-time","Payments product ownership.","Product Management,SQL,APIs","₹24L–₹42L","https://razorpay.com/jobs"),
    ("Product Manager","Flipkart","Bangalore","hybrid","full-time","Seller platform product.","Product Strategy,SQL,Data Analysis","₹26L–₹45L","https://www.flipkart.com/careers"),
    ("Product Manager","Meesho","Bangalore","hybrid","full-time","Social commerce product.","Product Management,SQL,Analytics","₹22L–₹38L","https://meesho.io/jobs"),
    ("Product Manager","Zomato","Gurgaon","hybrid","full-time","Consumer ordering product.","Product Strategy,SQL,Agile","₹24L–₹42L","https://www.zomato.com/careers"),
    ("Product Manager","CRED","Bangalore","hybrid","full-time","Premium fintech product.","Product Management,SQL,Analytics","₹26L–₹46L","https://careers.cred.club"),
    ("Product Manager","Hotstar","Mumbai","hybrid","full-time","Streaming and content product.","Product Strategy,Data Analysis,Agile","₹26L–₹45L","https://careers.hotstar.com"),
    ("Product Manager","Paytm","Noida","hybrid","full-time","Payments and wallet product.","Product Management,SQL,Analytics","₹22L–₹38L","https://paytm.com/careers"),
    ("Product Manager","Byju's","Bangalore","onsite","full-time","EdTech learning product.","Product Strategy,SQL,Analytics","₹20L–₹36L","https://byjus.com/careers"),
    ("Product Manager","Freshworks","Chennai","hybrid","full-time","SaaS CRM product.","Product Management,SQL,Agile","₹22L–₹38L","https://www.freshworks.com/company/careers"),
    ("Product Manager","PhonePe","Bangalore","hybrid","full-time","Digital payments product.","Product Management,SQL,Analytics","₹24L–₹42L","https://careers.phonepe.com"),
    ("Product Manager","Groww","Bangalore","hybrid","full-time","Investment product.","Product Management,SQL,Analytics","₹22L–₹38L","https://groww.in/about/careers"),
    ("Associate Product Manager","Groww","Bangalore","hybrid","full-time","Investment product features.","Product Management,SQL,Analytics","₹16L–₹28L","https://groww.in/about/careers"),
    ("Associate Product Manager","Urban Company","Gurgaon","hybrid","full-time","Services marketplace product.","Product Management,SQL","₹16L–₹28L","https://urbancompany.com/careers"),
    ("Associate Product Manager","Meesho","Bangalore","hybrid","full-time","Social commerce APM.","Product Thinking,SQL,Analytics","₹16L–₹28L","https://meesho.io/jobs"),
    ("Technical Product Manager","Amazon","Hyderabad","hybrid","full-time","AWS product management.","Product Strategy,SQL,APIs,AWS","₹32L–₹56L","https://amazon.jobs"),
    ("Senior Product Manager","Google","Hyderabad","hybrid","full-time","Google Pay product leadership.","Product Strategy,Data Analysis,Go-to-Market","₹40L–₹70L","https://careers.google.com"),
    ("Product Manager Intern","Razorpay","Bangalore","hybrid","internship","Payments product intern.","Product Thinking,SQL,Analytics","₹30K–₹50K/mo","https://razorpay.com/jobs"),
    ("Product Manager Intern","Zomato","Gurgaon","hybrid","internship","Consumer product intern.","Product Thinking,SQL","₹28K–₹45K/mo","https://www.zomato.com/careers"),
    ("Product Manager Intern","Swiggy","Bangalore","hybrid","internship","Food platform PM intern.","Product Thinking,SQL,Analytics","₹28K–₹45K/mo","https://bytes.swiggy.com/careers"),

    # ANDROID / MOBILE
    ("Android Developer","Swiggy","Bangalore","hybrid","full-time","Consumer food delivery Android app.","Kotlin,Java,Android SDK,MVVM","₹18L–₹32L","https://bytes.swiggy.com/careers"),
    ("Android Developer","PhonePe","Bangalore","hybrid","full-time","Payments Android application.","Kotlin,Android SDK,Jetpack","₹20L–₹36L","https://careers.phonepe.com"),
    ("Android Developer","Paytm","Noida","hybrid","full-time","Super-app Android development.","Kotlin,Java,Android SDK","₹16L–₹28L","https://paytm.com/careers"),
    ("Android Developer","Meesho","Bangalore","remote","full-time","Social commerce Android app.","Kotlin,Android SDK,Jetpack Compose","₹18L–₹32L","https://meesho.io/jobs"),
    ("Android Developer","Zomato","Gurgaon","hybrid","full-time","Food ordering Android experience.","Kotlin,Android SDK,MVVM","₹18L–₹32L","https://www.zomato.com/careers"),
    ("Android Developer","Ola","Bangalore","hybrid","full-time","Ride-hailing Android application.","Kotlin,Java,Maps SDK,MVVM","₹16L–₹28L","https://ola.careers"),
    ("Android Developer","Groww","Bangalore","hybrid","full-time","Investment Android app.","Kotlin,Jetpack Compose,MVVM","₹18L–₹32L","https://groww.in/about/careers"),
    ("Android Developer","Flipkart","Bangalore","hybrid","full-time","E-commerce buyer Android app.","Kotlin,Android SDK,MVVM","₹20L–₹36L","https://www.flipkart.com/careers"),
    ("iOS Developer","CRED","Bangalore","hybrid","full-time","Premium fintech iOS app.","Swift,SwiftUI,Objective-C,MVVM","₹22L–₹38L","https://careers.cred.club"),
    ("iOS Developer","Razorpay","Bangalore","hybrid","full-time","Payments iOS SDK and app.","Swift,Objective-C,UIKit","₹20L–₹36L","https://razorpay.com/jobs"),
    ("iOS Developer","Swiggy","Bangalore","hybrid","full-time","Food delivery iOS experience.","Swift,SwiftUI,MVVM","₹18L–₹32L","https://bytes.swiggy.com/careers"),
    ("iOS Developer","Hotstar","Mumbai","hybrid","full-time","Streaming iOS application.","Swift,AVFoundation,SwiftUI","₹20L–₹36L","https://careers.hotstar.com"),
    ("iOS Developer","Paytm","Noida","hybrid","full-time","Super-app iOS development.","Swift,SwiftUI,Objective-C","₹18L–₹32L","https://paytm.com/careers"),
    ("React Native Developer","Urban Company","Gurgaon","hybrid","full-time","Cross-platform services app.","React Native,TypeScript,Redux","₹16L–₹28L","https://urbancompany.com/careers"),
    ("React Native Developer","ShareChat","Remote","remote","full-time","Cross-platform social app.","React Native,TypeScript,Redux","₹16L–₹28L","https://sharechat.com/careers"),
    ("Flutter Developer","Slice","Bangalore","hybrid","full-time","Fintech cross-platform app.","Flutter,Dart,BLoC","₹15L–₹26L","https://sliceit.com/careers"),
    ("Flutter Developer","Lenskart","Remote","remote","full-time","Optical e-commerce app.","Flutter,Dart,Firebase","₹14L–₹24L","https://careers.lenskart.com"),
    ("Senior Android Developer","Flipkart","Bangalore","hybrid","full-time","Lead buyer Android experience.","Kotlin,Jetpack Compose,MVVM","₹30L–₹52L","https://www.flipkart.com/careers"),
    ("Senior iOS Developer","Paytm","Noida","hybrid","full-time","Lead payments iOS team.","Swift,SwiftUI,Objective-C","₹28L–₹48L","https://paytm.com/careers"),
    ("Mobile Developer Intern","PhonePe","Bangalore","hybrid","internship","Payments mobile features.","Kotlin,Java,Android","₹22K–₹38K/mo","https://careers.phonepe.com"),
    ("Mobile Developer Intern","Swiggy","Bangalore","onsite","internship","Delivery app mobile intern.","Kotlin,Swift","₹20K–₹35K/mo","https://bytes.swiggy.com/careers"),

    # DATA ENGINEERING
    ("Data Engineer","Flipkart","Bangalore","hybrid","full-time","Build petabyte-scale data pipelines.","Python,Spark,Kafka,Hive,SQL","₹18L–₹32L","https://www.flipkart.com/careers"),
    ("Data Engineer","Amazon","Hyderabad","hybrid","full-time","AWS data lake and ETL pipelines.","Python,Spark,AWS Glue,Redshift","₹22L–₹40L","https://amazon.jobs"),
    ("Data Engineer","Swiggy","Bangalore","hybrid","full-time","Food delivery data pipelines.","Python,Spark,Kafka,Airflow","₹20L–₹36L","https://bytes.swiggy.com/careers"),
    ("Data Engineer","PhonePe","Bangalore","hybrid","full-time","Payments data infrastructure.","Python,Spark,Kafka,Hive","₹20L–₹36L","https://careers.phonepe.com"),
    ("Data Engineer","Meesho","Remote","remote","full-time","Social commerce data platform.","Python,Spark,Airflow,dbt","₹18L–₹32L","https://meesho.io/jobs"),
    ("Data Engineer","Razorpay","Bangalore","hybrid","full-time","Payments analytics infrastructure.","Python,Spark,Kafka,dbt","₹18L–₹32L","https://razorpay.com/jobs"),
    ("Data Engineer","Hotstar","Mumbai","hybrid","full-time","Streaming data platform.","Python,Spark,Kafka,Flink","₹20L–₹36L","https://careers.hotstar.com"),
    ("Data Engineer","Zomato","Gurgaon","hybrid","full-time","Food platform data pipelines.","Python,Spark,Airflow,BigQuery","₹18L–₹32L","https://www.zomato.com/careers"),
    ("Data Engineer","Delhivery","Remote","remote","full-time","Logistics data infrastructure.","Python,Spark,Airflow,SQL","₹16L–₹28L","https://www.delhivery.com/careers"),
    ("Data Engineer","ShareChat","Remote","remote","full-time","Social media data platform.","Python,Spark,Kafka,Airflow","₹18L–₹32L","https://sharechat.com/careers"),
    ("Data Engineer","Dunzo","Remote","remote","full-time","Quick commerce data engineering.","Python,Airflow,BigQuery,dbt","₹15L–₹26L","https://www.dunzo.com/careers"),
    ("Data Engineer","Paytm","Noida","hybrid","full-time","Payments data lake and pipelines.","Python,Spark,Hive,SQL","₹16L–₹28L","https://paytm.com/careers"),
    ("Senior Data Engineer","Google","Hyderabad","hybrid","full-time","Lead data platform for Google India.","Python,Spark,BigQuery,Dataflow","₹38L–₹65L","https://careers.google.com"),
    ("Data Engineer Intern","Flipkart","Bangalore","hybrid","internship","Data pipeline intern.","Python,Spark,SQL","₹22K–₹38K/mo","https://www.flipkart.com/careers"),
    ("Data Engineer Intern","Amazon","Hyderabad","hybrid","internship","AWS data engineering intern.","Python,SQL,AWS","₹25K–₹40K/mo","https://amazon.jobs"),
    ("Contract Data Engineer","Remote","Remote","remote","contract","3-month data pipeline modernisation.","Python,Spark,Airflow,dbt","₹80K–₹1.1L/mo","https://angel.co/jobs"),

    # QA / TESTING
    ("QA Engineer","BrowserStack","Mumbai","hybrid","full-time","Test automation platform quality.","Selenium,Python,Java,TestNG","₹10L–₹18L","https://www.browserstack.com/careers"),
    ("QA Engineer","Freshworks","Chennai","hybrid","full-time","CRM product quality assurance.","Selenium,Python,Pytest,REST","₹10L–₹18L","https://www.freshworks.com/company/careers"),
    ("QA Engineer","Chargebee","Chennai","hybrid","full-time","Billing product testing.","Selenium,Python,Postman,TestNG","₹10L–₹18L","https://www.chargebee.com/careers"),
    ("QA Engineer","Zoho","Chennai","onsite","full-time","Enterprise product testing.","Selenium,Java,TestNG,SQL","₹8L–₹15L","https://careers.zohocorp.com"),
    ("QA Engineer","PhonePe","Bangalore","hybrid","full-time","Payments platform testing.","Selenium,Python,Appium,REST","₹12L–₹22L","https://careers.phonepe.com"),
    ("QA Engineer","Razorpay","Bangalore","hybrid","full-time","Payments API testing.","Selenium,Python,Postman,TestNG","₹12L–₹22L","https://razorpay.com/jobs"),
    ("QA Engineer","Groww","Bangalore","hybrid","full-time","Trading platform QA.","Selenium,Java,Appium,TestNG","₹10L–₹18L","https://groww.in/about/careers"),
    ("SDET","Razorpay","Bangalore","hybrid","full-time","Software development engineer in test.","Python,Go,Selenium,Pytest","₹14L–₹24L","https://razorpay.com/jobs"),
    ("SDET","Flipkart","Bangalore","hybrid","full-time","E-commerce platform SDET.","Java,Selenium,TestNG,Docker","₹16L–₹28L","https://www.flipkart.com/careers"),
    ("Automation Test Engineer","TCS","Pune","hybrid","full-time","Enterprise test automation.","Selenium,Java,TestNG,SQL","₹8L–₹15L","https://www.tcs.com/careers"),
    ("Automation Test Engineer","Infosys","Bangalore","hybrid","full-time","Digital product test automation.","Selenium,Python,Pytest,REST","₹9L–₹16L","https://www.infosys.com/careers"),
    ("Performance Test Engineer","Hotstar","Mumbai","hybrid","full-time","Streaming platform load testing.","JMeter,Gatling,Python,AWS","₹14L–₹24L","https://careers.hotstar.com"),
    ("QA Intern","BrowserStack","Mumbai","hybrid","internship","Test automation intern.","Selenium,Python,Java","₹18K–₹30K/mo","https://www.browserstack.com/careers"),
    ("QA Intern","Freshworks","Chennai","onsite","internship","Product QA intern.","Selenium,Python,SQL","₹15K–₹25K/mo","https://www.freshworks.com/company/careers"),
    ("QA Intern","Razorpay","Bangalore","hybrid","internship","Payments testing intern.","Python,Selenium,Postman","₹18K–₹30K/mo","https://razorpay.com/jobs"),

    # BLOCKCHAIN
    ("Blockchain Developer","CoinDCX","Bangalore","remote","full-time","Crypto exchange smart contracts.","Solidity,Web3.js,Ethereum,Python","₹18L–₹32L","https://coindcx.com/careers"),
    ("Blockchain Developer","WazirX","Mumbai","remote","full-time","DeFi and NFT platform.","Solidity,Ethereum,Node.js,Web3","₹16L–₹28L","https://wazirx.com/careers"),
    ("Smart Contract Developer","CoinSwitch","Bangalore","remote","full-time","DeFi protocol development.","Solidity,Hardhat,Ethers.js","₹18L–₹32L","https://coinswitch.co/careers"),
    ("Web3 Developer","Polygon","Remote","remote","full-time","Layer 2 scaling solution.","Solidity,Go,Rust,Web3.js","₹25L–₹45L","https://polygon.technology/careers"),
    ("Blockchain Intern","CoinDCX","Remote","remote","internship","Smart contract development intern.","Solidity,Web3.js,Python","₹20K–₹35K/mo","https://coindcx.com/careers"),

    # AI / NLP
    ("NLP Engineer","ShareChat","Bangalore","remote","full-time","Vernacular NLP for Indian languages.","Python,NLP,HuggingFace,PyTorch","₹22L–₹40L","https://sharechat.com/careers"),
    ("NLP Engineer","Sarvam AI","Bangalore","hybrid","full-time","Build Indian language AI models.","Python,PyTorch,HuggingFace,Transformers","₹25L–₹45L","https://sarvam.ai/careers"),
    ("NLP Engineer","Vernacular.ai","Bangalore","hybrid","full-time","Conversational AI for enterprises.","Python,NLP,BERT,FastAPI","₹18L–₹32L","https://vernacular.ai/careers"),
    ("AI Engineer","Krutrim","Bangalore","hybrid","full-time","Build Indian foundational AI models.","Python,PyTorch,CUDA,Distributed Training","₹28L–₹50L","https://olakrutrim.com/careers"),
    ("AI Engineer","Jio","Mumbai","hybrid","full-time","AI products for Jio ecosystem.","Python,TensorFlow,ML,APIs","₹20L–₹36L","https://careers.jio.com"),
    ("Generative AI Engineer","Infosys","Bangalore","hybrid","full-time","Enterprise GenAI solutions.","Python,LangChain,OpenAI APIs,RAG","₹16L–₹30L","https://www.infosys.com/careers"),
    ("Generative AI Engineer","TCS","Pune","hybrid","full-time","GenAI product development.","Python,LangChain,LLMs,RAG","₹16L–₹28L","https://www.tcs.com/careers"),
    ("Generative AI Engineer","Wipro","Hyderabad","hybrid","full-time","Enterprise LLM implementation.","Python,LangChain,OpenAI,RAG","₹15L–₹28L","https://careers.wipro.com"),
    ("Computer Vision Engineer","Ola","Bangalore","hybrid","full-time","Autonomous vehicle perception.","Python,OpenCV,PyTorch,CUDA","₹22L–₹40L","https://ola.careers"),
    ("Computer Vision Engineer","Lenskart","Remote","remote","full-time","AR try-on and frame detection.","Python,OpenCV,TensorFlow,CUDA","₹18L–₹32L","https://careers.lenskart.com"),
    ("Research Scientist","Google DeepMind","Hyderabad","hybrid","full-time","AI research and publications.","Python,PyTorch,Mathematics,Research","₹45L–₹80L","https://careers.google.com"),
    ("Research Scientist","Microsoft Research","Hyderabad","hybrid","full-time","Applied AI and ML research.","Python,PyTorch,Research,Mathematics","₹40L–₹70L","https://careers.microsoft.com"),
    ("AI Research Intern","IISc","Bangalore","onsite","internship","Academic AI research internship.","Python,PyTorch,Research","Stipend","https://iisc.ac.in"),
    ("AI Research Intern","Sarvam AI","Bangalore","hybrid","internship","Indian language AI research.","Python,PyTorch,NLP","Stipend","https://sarvam.ai/careers"),
    ("Research Engineer Intern","Google","Bangalore","hybrid","internship","AI product research intern.","Python,TensorFlow,ML","Stipend","https://careers.google.com"),
    ("Research Engineer Intern","Microsoft","Hyderabad","hybrid","internship","Azure AI research intern.","Python,PyTorch,ML","Stipend","https://careers.microsoft.com"),
    ("Part-time AI Engineer","Remote","Remote","remote","part-time","AI consulting and model building.","Python,ML,OpenAI APIs,FastAPI","₹60K–₹90K/mo","https://angel.co/jobs"),

    # SPECIALISED / MISC
    ("Database Administrator","Wipro","Hyderabad","hybrid","full-time","Oracle and MySQL DBA for enterprise.","Oracle,MySQL,SQL,Linux","₹10L–₹18L","https://careers.wipro.com"),
    ("Database Administrator","TCS","Pune","onsite","full-time","Enterprise database management.","Oracle,SQL Server,MySQL","₹10L–₹18L","https://www.tcs.com/careers"),
    ("Database Engineer","Razorpay","Bangalore","hybrid","full-time","Payments database engineering.","MySQL,PostgreSQL,Vitess,SQL","₹18L–₹32L","https://razorpay.com/jobs"),
    ("Elasticsearch Engineer","ShareChat","Remote","remote","full-time","Search platform engineering.","Elasticsearch,Kibana,Python,Java","₹16L–₹28L","https://sharechat.com/careers"),
    ("Embedded Systems Engineer","Bosch","Pune","onsite","full-time","Automotive ECU firmware.","C,C++,Embedded C,CAN Bus","₹12L–₹22L","https://www.bosch-india.com/careers"),
    ("Embedded Systems Engineer","Ola Electric","Bangalore","onsite","full-time","EV firmware development.","C,C++,RTOS,CAN Bus","₹16L–₹28L","https://olaelectric.com/careers"),
    ("Firmware Engineer","Ather Energy","Bangalore","onsite","full-time","Scooter embedded firmware.","C,C++,Linux,RTOS","₹14L–₹24L","https://atherenergy.com/careers"),
    ("Network Engineer","Jio","Mumbai","onsite","full-time","Telecom network design.","Networking,CCNA,Python,Linux","₹10L–₹18L","https://careers.jio.com"),
    ("Network Engineer","Wipro","Hyderabad","hybrid","full-time","Enterprise network infrastructure.","Networking,Cisco,Python,Linux","₹10L–₹18L","https://careers.wipro.com"),
    ("Solutions Architect","AWS","Hyderabad","hybrid","full-time","Architect cloud solutions for India.","AWS,Solution Design,Python,Networking","₹35L–₹60L","https://amazon.jobs"),
    ("Solutions Architect","Microsoft","Hyderabad","hybrid","full-time","Azure solutions for enterprise clients.","Azure,Solution Design,.NET,Networking","₹32L–₹56L","https://careers.microsoft.com"),
    ("Technical Writer","Freshworks","Chennai","remote","full-time","API and product documentation.","Technical Writing,Markdown,REST APIs","₹8L–₹15L","https://www.freshworks.com/company/careers"),
    ("Technical Writer","Hasura","Remote","remote","full-time","GraphQL and developer docs.","Technical Writing,GraphQL,Markdown","₹10L–₹18L","https://hasura.io/careers"),
    ("Developer Advocate","Postman","Bangalore","hybrid","full-time","API developer community and content.","REST APIs,Technical Writing,Public Speaking","₹16L–₹28L","https://www.postman.com/company/careers"),
    ("Developer Advocate","Hasura","Remote","remote","full-time","GraphQL ecosystem developer advocacy.","GraphQL,Technical Writing,Developer Relations","₹18L–₹32L","https://hasura.io/careers"),
    ("Scrum Master","Infosys","Bangalore","hybrid","full-time","Agile delivery for digital projects.","Agile,Scrum,Jira,Confluence","₹12L–₹22L","https://www.infosys.com/careers"),
    ("Scrum Master","Wipro","Hyderabad","hybrid","full-time","Enterprise agile transformation.","Agile,Scrum,SAFe,Jira","₹12L–₹22L","https://careers.wipro.com"),
    ("Tech Lead","Razorpay","Bangalore","hybrid","full-time","Lead engineering team for payments.","Java,Go,System Design,Leadership","₹35L–₹60L","https://razorpay.com/jobs"),
    ("Tech Lead","PhonePe","Bangalore","hybrid","full-time","Lead high-throughput payment systems.","Java,Kafka,System Design,Leadership","₹38L–₹65L","https://careers.phonepe.com"),
    ("Engineering Manager","Flipkart","Bangalore","hybrid","full-time","Manage buyer platform engineering.","Engineering Management,Java,System Design","₹45L–₹80L","https://www.flipkart.com/careers"),
    ("Engineering Manager","Swiggy","Bangalore","hybrid","full-time","Lead food delivery backend team.","Engineering Management,Go,System Design","₹42L–₹75L","https://bytes.swiggy.com/careers"),
    ("Quantitative Analyst","Zerodha","Bangalore","hybrid","full-time","Algo trading strategy development.","Python,Statistics,ML,SQL","₹20L–₹36L","https://zerodha.com/careers"),
    ("Quantitative Analyst","Groww","Bangalore","hybrid","full-time","Investment product quant models.","Python,R,Statistics,SQL","₹18L–₹32L","https://groww.in/about/careers"),
    ("Risk Analyst","Razorpay","Bangalore","hybrid","full-time","Payments risk and fraud modelling.","Python,SQL,Statistics,ML","₹14L–₹24L","https://razorpay.com/jobs"),
    ("Risk Analyst","CRED","Bangalore","hybrid","full-time","Credit risk and underwriting.","Python,SQL,Statistics","₹14L–₹24L","https://careers.cred.club"),
    ("Financial Analyst","Paytm","Noida","hybrid","full-time","Financial modelling and forecasting.","Excel,SQL,Python,PowerBI","₹10L–₹18L","https://paytm.com/careers"),
    ("Financial Analyst Intern","Deloitte","Remote","remote","internship","Financial modelling intern.","Excel,PowerPoint,SQL","₹20K–₹35K/mo","https://www2.deloitte.com/in/en/careers"),
    ("CTO Startup","YC-backed Startup","Remote","remote","full-time","Build and lead early-stage startup engineering.","System Design,Cloud,Leadership,Full Stack","₹30L–₹60L + Equity","https://angel.co/jobs"),
    ("Contract ML Engineer","Remote","Remote","remote","contract","6-month MLOps implementation.","Python,MLFlow,Kubernetes,Docker","₹90K–₹1.2L/mo","https://angel.co/jobs"),
]


def create_database(force: bool = False):
    if os.path.exists(DB_PATH):
        if not force:
            print(f"✅  {DB_PATH} already exists — skipping seed (use --force to rebuild).")
            return
        os.remove(DB_PATH)
        print(f"Removed existing {DB_PATH}")

    parent = os.path.dirname(DB_PATH)
    if parent:
        os.makedirs(parent, exist_ok=True)

    conn = sqlite3.connect(DB_PATH)
    cur  = conn.cursor()
    cur.execute(CREATE_TABLE)

    cur.executemany("""
        INSERT INTO jobs
            (job_title, company, location, work_mode, job_type,
             description, required_skills, salary_range, apply_link)
        VALUES (?,?,?,?,?,?,?,?,?)
    """, JOBS)

    conn.commit()
    total = cur.execute("SELECT COUNT(*) FROM jobs").fetchone()[0]
    print(f"\n✅  Created {DB_PATH} with {total} job listings")
    print(f"    Unique titles  : {len(set(j[0] for j in JOBS))}")
    print(f"    Work modes     : {sorted(set(j[3] for j in JOBS))}")
    print(f"    Job types      : {sorted(set(j[4] for j in JOBS))}")
    print(f"    Locations      : {len(set(j[2] for j in JOBS))} unique")
    conn.close()


if __name__ == "__main__":
    import sys
    create_database(force="--force" in sys.argv)